Replace old files with latest VLC version

diff --git a/vlc/contrib/bootstrap b/vlc/contrib/bootstrap
--- a/vlc/contrib/bootstrap
+++ b/vlc/contrib/bootstrap
@@ -52,12 +52,6 @@ AD_CLAUSES=
 WITH_OPTIMIZATION="1"
 ENABLE_PDB=
 
-if test ! -f "../../contrib/src/main.mak"
-then
-	echo "$0 must be run from a subdirectory"
-	exit 1
-fi
-
 while test -n "$1"
 do
 	case "$1" in
@@ -124,7 +118,7 @@ fi
 
 if test -z "$BUILD"
 then
-	echo -n "Guessing build system... "
+	printf "Guessing build system... "
 	BUILD="`${CC:-cc} -dumpmachine | sed s/windows-gnu/mingw32/`"
 	if test -z "$BUILD"; then
 		echo "FAIL!"
@@ -135,12 +129,12 @@ fi
 
 if test -z "$HOST"
 then
-	echo -n "Guessing host system...  "
+	printf "Guessing host system...  "
 	HOST="$BUILD"
 	echo "$HOST"
 fi
 
-echo -n "Packages licensing...    "
+printf "Packages licensing...    "
 if test -n "$GPL"
 then
 	if test -n "$GNUV3"
@@ -201,40 +195,40 @@ add_make_enabled()
 
 check_ios_sdk()
 {
-    if test "$VLCSDKROOT"
-    then
-	    SDKROOT="$VLCSDKROOT"
-    else
+	if test "$VLCSDKROOT"
+	then
+		SDKROOT="$VLCSDKROOT"
+	else
 		if test -z "$SDKROOT"
 		then
-		   SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
-		   echo "SDKROOT not specified, assuming $SDKROOT"
+			SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
+			echo "SDKROOT not specified, assuming $SDKROOT"
 		else
-		   SDKROOT="$SDKROOT"
+			SDKROOT="$SDKROOT"
 		fi
-    fi
+	fi
 
-    if [ ! -d "${SDKROOT}" ]
-    then
-       echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
-       exit 1
-    fi
-    add_make "IOS_SDK=${SDKROOT}"
+	if [ ! -d "${SDKROOT}" ]
+	then
+		echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
+		exit 1
+	fi
+	add_make "IOS_SDK=${SDKROOT}"
 }
 
 check_macosx_sdk()
 {
-   if [ -z "$SDKROOT" ]; then
-      SDKROOT=$(xcrun --show-sdk-path)
-      echo "SDKROOT not specified, assuming $SDKROOT"
-   fi
+	if [ -z "$SDKROOT" ]; then
+		SDKROOT=$(xcrun --show-sdk-path)
+		echo "SDKROOT not specified, assuming $SDKROOT"
+	fi
 
-   if [ ! -d "$SDKROOT" ]; then
-      echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
-      exit 1
-   fi
+	if [ ! -d "$SDKROOT" ]; then
+		echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
+		exit 1
+	fi
 
-   add_make "MACOSX_SDK=${SDKROOT}"
+	add_make "MACOSX_SDK=${SDKROOT}"
 }
 
 check_android_sdk()
@@ -250,16 +244,6 @@ check_android_sdk()
 	[ ${ANDROID_ABI} = "arm64-v8a" ] && add_make_enabled "HAVE_NEON"
 	[ ${ANDROID_ABI} = "arm64-v8a" ] && add_make_enabled "HAVE_ARMV8A"
 	[ ${ANDROID_ABI} = "armeabi" -a -z "${NO_ARMV6}" ] && add_make_enabled "HAVE_ARMV6"
-}
-
-check_tizen_sdk()
-{
-	[ -z "${TIZEN_SDK}" ] && echo "You must set TIZEN_SDK environment variable" && exit 1
-	add_make "TIZEN_SDK := ${TIZEN_SDK}"
-	[ -z "${TIZEN_ABI}" ] && echo "You must set TIZEN_ABI environment variable" && exit 1
-	add_make "TIZEN_ABI := ${TIZEN_ABI}"
-	[ ${TIZEN_ABI} = "armv7l" ] && add_make_enabled "HAVE_NEON"
-	[ ${TIZEN_ABI} = "armv7l" ] && add_make_enabled "HAVE_ARMV7A"
 }
 
 test -z "$PREFIX" || add_make "PREFIX := $PREFIX"
@@ -289,23 +273,23 @@ case "${OS}" in
 			add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_FPU"
 
 			case "${HOST}" in
-			    *armv7s*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7s"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm64*|*aarch64*)
-			    add_make "PLATFORM_SHORT_ARCH := arm64"
-			    ;;
-			    *x86_64*)
-			    add_make "PLATFORM_SHORT_ARCH := x86_64"
-			    ;;
-			    *86*)
-			    add_make "PLATFORM_SHORT_ARCH := i386"
-			    ;;
+				*armv7s*)
+					add_make "PLATFORM_SHORT_ARCH := armv7s"
+					add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+					;;
+				*arm64*|*aarch64*)
+					add_make "PLATFORM_SHORT_ARCH := arm64"
+					;;
+				*arm*)
+					add_make "PLATFORM_SHORT_ARCH := armv7"
+					add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+					;;
+				*x86_64*)
+					add_make "PLATFORM_SHORT_ARCH := x86_64"
+					;;
+				*86*)
+					add_make "PLATFORM_SHORT_ARCH := i386"
+					;;
 			esac;
 		fi
 		if test "$BUILDFORTVOS"
@@ -320,61 +304,43 @@ case "${OS}" in
 		check_android_sdk
 		add_make_enabled "HAVE_LINUX" "HAVE_ANDROID"
 		case "${HOST}" in
-			*arm*)
-			add_make "PLATFORM_SHORT_ARCH := arm"
-			;;
 			*arm64*|*aarch64*)
-			add_make "PLATFORM_SHORT_ARCH := arm64"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := arm64"
+				;;
+			*arm*)
+				add_make "PLATFORM_SHORT_ARCH := arm"
+				;;
 			*i686*)
-			add_make "PLATFORM_SHORT_ARCH := x86"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := x86"
+				;;
 			*x86_64*)
-			add_make "PLATFORM_SHORT_ARCH := x86_64"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := x86_64"
+				;;
 			*mipsel*)
-			add_make "PLATFORM_SHORT_ARCH := mips"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := mips"
+				;;
 		esac
 		;;
 	*linux*)
-		if [ "`${CC} -v 2>&1 | grep tizen`" ]; then
-			check_tizen_sdk
-			add_make_enabled "HAVE_TIZEN"
-			case "${HOST}" in
-				*arm*)
-				add_make "PLATFORM_SHORT_ARCH := arm"
-				;;
-				*i386*)
-				add_make "PLATFORM_SHORT_ARCH := x86"
-				;;
-			esac
-		fi
-
 		add_make_enabled "HAVE_LINUX"
 		;;
 	*mingw*)
 		add_make_enabled "HAVE_WIN32"
 		case "${HOST}" in
 			*winphone*|*windowsphone*)
-			add_make_enabled "HAVE_WINDOWSPHONE"
-			;;
+				add_make_enabled "HAVE_WINDOWSPHONE"
+				;;
 		esac
 		case "${HOST}" in
 			*winphone*|*windowsphone*|*winrt*|*uwp*)
-			add_make_enabled "HAVE_WINSTORE"
-			;;
+				add_make_enabled "HAVE_WINSTORE"
+				;;
 		esac
 		case "${HOST}" in
-			amd64*|x86_64*)
-			add_make_enabled "HAVE_WIN64"
-			;;
+			armv7*)
+				add_make_enabled "HAVE_ARMV7A"
+				;;
 		esac
-        case "${HOST}" in
-            armv7*)
-                add_make_enabled "HAVE_ARMV7A"
-                ;;
-        esac
 		;;
 	*solaris*)
 		add_make_enabled "HAVE_SOLARIS"
@@ -387,10 +353,16 @@ esac
 #
 # Results output
 #
-echo TOPSRC = .. >> Makefile
-echo TOPSRC_BUILT = ../.. >> Makefile
-echo TOPDST = .. >> Makefile
-echo include $\(TOPSRC\)/src/main.mak >> Makefile
+BOOTSTRAP_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
+CURRENT_PATH="$( pwd -P )"
+# location of the contrib/src folder from the root of the contrib build folder
+TOPSRC=$(python3 -c "import os; print(os.path.relpath('$BOOTSTRAP_PATH', '$CURRENT_PATH'))")
+# location of the contrib/src folder from a built library folder
+TOPSRC_BUILT=$(python3 -c "import os; print(os.path.relpath('$BOOTSTRAP_PATH', '$CURRENT_PATH/libfoo'))")
+add_make "TOPSRC = $TOPSRC"
+add_make "TOPSRC_BUILT = $TOPSRC_BUILT"
+add_make "TOPDST = .."
+add_make 'include $(TOPSRC)/src/main.mak'
 echo "Bootstrap completed."
 make help
-mkdir -p ../../contrib/tarballs || exit $?
+mkdir -p $BOOTSTRAP_PATH/tarballs || exit $?
